[package]
name = "test-runtime"
version = "0.24.0"
edition = "2021"

[dependencies]
subxt = { path = "../../subxt" }
sp-runtime = { package = "sp-runtime", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
    "derive",
    "full",
    "bit-vec",
] }

[build-dependencies]
subxt = { path = "../../subxt" }
sp-core = { package = "sp-core", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.30", default-features = false }
tokio = { version = "1.8", features = ["macros", "rt-multi-thread"] }
which = "4.2.2"
jsonrpsee = { version = "0.15.1", features = [
    "async-client",
    "client-ws-transport",
] }
